export const french = [
  "abandonner", "abîme", "abonnement", "aborder", "aboutir", "abri", "absence", "absolu", "absurde", "abuser",
  "accepter", "accident", "accompagner", "accord", "accrocher", "accueil", "acheter", "acide", "acquérir", "actif",
  "acteur", "actif", "adapter", "adresse", "adversaire", "affaire", "affecter", "affiche", "affirmer", "agence",
  "agilité", "agréable", "aider", "aigle", "aile", "aimer", "aîné", "air", "ajouter", "aléatoire", "alcool",
  "allemand", "allumer", "alors", "amener", "amitié", "amour", "analyse", "analyser", "ancien", "année",
  "annoncer", "anonyme", "apaiser", "apercevoir", "apprendre", "après", "arrêter", "arriver", "art", "article",
  "ascenseur", "assister", "associé", "assurance", "attendre", "attirer", "attitude", "avancer", "aventure",
  "avenir", "avertir", "avion", "avoir", "avouer", "baccalauréat", "bague", "baisser", "balade", "balle",
  "banque", "baptême", "barrière", "bassin", "bataille", "bavarder", "beau", "beauté", "bénéfice", "besoin",
  "bête", "biais", "bientôt", "billet", "blanc", "blesser", "blessure", "boîte", "bonheur", "bord", "bouche",
  "boulanger", "bourse", "bravo", "bref", "briller", "brise", "broder", "brouillon", "brouillard", "bruit",
  "brun", "bureau", "cacher", "café", "calme", "cancer", "canal", "candidat", "capable", "capital", "carte",
  "casser", "cauchemar", "céder", "célébrer", "censurer", "cerf", "chambre", "chance", "changer", "chanson",
  "chaos", "chapeau", "chasser", "chat", "chiffre", "chimie", "chiffon", "choisir", "chose", "chouette",
  "cicatrice", "ciel", "cigarette", "ciment", "cinq", "circuit", "citer", "clarté", "classe", "climat",
  "cloche", "clou", "clique", "cloche", "clore", "clou", "clown", "coeur", "colis", "colle", "colline",
  "combien", "comique", "comité", "compte", "concerner", "confiance", "conseil", "construire", "content",
  "contrat", "copain", "copie", "corps", "côté", "coucher", "couleur", "coup", "courir", "couronne",
  "cousin", "couteau", "couvert", "crabe", "crâne", "crayon", "création", "crier", "croire", "croissant",
  "croix", "cruel", "cuisine", "curieux", "danger", "danser", "décider", "découvrir", "défendre", "déjeuner",
  "délai", "demander", "démolir", "démontre", "dent", "départ", "dépêcher", "déranger", "désirer", "désolé",
  "désordre", "dessiner", "détail", "détente", "devoir", "deviner", "différent", "difficile", "dîner",
  "diplôme", "dire", "discret", "dossier", "doute", "doux", "drapeau", "droit", "dur", "durer",
  "écart", "écrire", "éducation", "effacer", "effet", "effort", "élargir", "électrique", "élève", "énergie",
  "enfant", "enfer", "enfin", "ensemble", "entendre", "entraîner", "envie", "équipe", "erreur", "espace",
  "essayer", "estimer", "état", "éternel", "étudier", "éventuel", "examen", "excuse", "exemple", "exister",
  "expliquer", "extrait", "facile", "faim", "faire", "fameux", "femme", "fenêtre", "fermer", "fête",
  "fichier", "fille", "film", "finir", "fixer", "flamme", "flatter", "fleur", "fleurir", "fleuriste",
  "fleuriste", "foire", "fois", "forêt", "formel", "fort", "fou", "fouiller", "fraise", "frère",
  "froid", "front", "fuir", "fumer", "futur", "gagner", "garçon", "gâteau", "gauche", "génial", "gérer",
  "gilet", "glace", "glisser", "goût", "gouverner", "grand", "grâce", "grâce", "gratter", "grille",
  "groupe", "guérir", "habiter", "histoire", "homme", "honte", "horizon", "hôtel", "huit", "idée",
  "image", "imiter", "important", "impression", "informer", "inscrire", "intéressant", "inviter", "jambe",
  "jardin", "jeune", "joie", "jouer", "jour", "journer", "juillet", "jumeau", "jurer", "juste", "juteux",
  "lancer", "langue", "laver", "légume", "lettre", "liberté", "lien", "lire", "livre", "loger", "louer",
  "lumière", "lundi", "lutte", "magasin", "magique", "maison", "malade", "manger", "mariage", "marié",
  "même", "mémoire", "merci", "métier", "mettre", "mignon", "mille", "minute", "moi", "monde",
  "montagne", "mouvement", "moyen", "mugir", "musée", "nager", "naissance", "narratif", "nature", "neige",
  "nervosité", "nettoyer", "nuit", "numéro", "obéir", "obliger", "offrir", "ombre", "oncle", "opinion",
  "ouvrir", "page", "pain", "parler", "partir", "passer", "patience", "payer", "peindre", "père", "perdre",
  "permettre", "personne", "petit", "peu", "plage", "plaire", "plan", "plante", "plat", "plonger",
  "pluie", "point", "police", "porte", "poser", "possible", "prénom", "prendre", "préparer", "présenter",
  "prêter", "problème", "produire", "promettre", "protéger", "prouver", "public", "qualité", "quitter",
  "raison", "ranger", "rappeler", "réaliser", "réfléchir", "répondre", "rester", "rien", "saison", "salir",
  "salut", "savoir", "scène", "semaine", "sérieux", "servir", "si", "simple", "société", "soir",
  "solide", "sommeil", "sortir", "sous", "souvenir", "sourire", "souscrire", "soutenir", "souvent", "sujet",
  "super", "sur", "table", "téléphone", "temps", "terminer", "tête", "travailler", "très", "trouver",
  "tuer", "un", "unique", "utile", "valeur", "vendre", "venir", "verbe", "vérifier", "vers", "vert",
  "ville", "voir", "voler", "vouloir", "vrai", "vraiment", "vulnérable", "yoga", "zéro"
];
