name: Deploy React Vite to GitHub Pages

on:
  push:
    branches:
      - main   # Wird ausgelöst, wenn du in main pusht

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # Läuft auf nem Linux-Server

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist